### PR TITLE
Improve private server support (Closes #9)

### LINKED ISSUE #9: Private server support
With the latest release and the update of the api, the private server support has been undone as well.
Is there any roadmap on reintroducing this feature?

### PR DESCRIPTION
**Pull request by FancyFurret**
I have added improved private server support!:
* Leaving token blank in config setup lets the user put in their server url, port, username, and password
* Gets a token from the api using that information

### CODE REVIEW

**Comment by CGamesPlay** [comment]
Hi @osum4est, thanks for contributing! After looking over the code it looks pretty reasonable, but I think the user experience seems a bit unintuitive to me. Just so I understand correctly:

- If you want to connect to production, put in your API token.
- If you want to use a private server, put in a host/port/username/password.
- The http / https thing is nothing the user cares about, it's just a private server / production server implementation detail.

Assuming this is correct, can you extend the [installation documentation](https://github.com/screepers/screeps-multimeter#installation) to add a bit more color about how exactly it works? I saw your note in the NUX prompt, but a little more explanation would make it easier for new users.

Also, do private servers have shard support? I'm a little out of touch :)

Thanks again for contributing! I'm in favor of merging this with a little work.

**Comment by FancyFurret** [comment]
Thanks for taking a look at it! You are correct, leaving the api token blank will allow the user to enter the hostname, port, username, and password. 

I didn't ask the user whether it is http or https, since private servers only really support http. (Well, the steam client will force http on a private server, so you're stuck with that). I kept https for connecting to the official server.

This: https://blog.screeps.com/2017/08/shards/ article says they were added to the private server, however I haven't personally tried using them. 

As far as user experience goes, I would have preferred some kind of choice, a dropdown, multiple buttons, etc. but I couldn't figure out how to do that easily, so I just extended what you already had.

I'll go ahead and update the install docs!

**Comment by CGamesPlay** [comment]
Thanks for updating! I'll push a new version out later this week, and all clients will auto update after that!

**Comment by CGamesPlay** [comment]
Following up, I've just push 1.7.0 including this change. Thanks again!

**Pull request merged**
